In [9]:
# Matthew McCarroll created 8/31/2020
import numpy as np
import pandas as pd

In [10]:
# opens the downloaded file from https://www.eia.gov/dnav/pet/pet_crd_crpdn_adc_mbblpd_m.htm
xls = pd.ExcelFile('PET_CRD_CRPDN_ADC_MBBLPD_M.xls')
data = pd.read_excel(xls, 'Data 1', skiprows=2)

In [11]:
data.tail()

,Date,U.S. Field Production of Crude Oil (Thousand Barrels per Day),East Coast (PADD 1) Field Production of Crude Oil (Thousand Barrels per Day),Florida Field Production of Crude Oil (Thousand Barrels per Day),New York Field Production of Crude Oil (Thousand Barrels per Day),Pennsylvania Field Production of Crude Oil (Thousand Barrels per Day),Virginia Field Production of Crude Oil (Thousand Barrels per Day),West Virginia Field Production of Crude Oil (Thousand Barrels per Day),Midwest (PADD 2) Field Production of Crude Oil (Thousand Barrels per Day),Illinois Field Production of Crude Oil (Thousand Barrels per Day),...,Utah Field Production of Crude Oil (Thousand Barrels per Day),Wyoming Field Production of Crude Oil (Thousand Barrels per Day),West Coast (PADD 5) Field Production of Crude Oil (Thousand Barrels per Day),Alaska Field Production of Crude Oil (Thousand Barrels per Day),Alaska South Field Production of Crude Oil (Thousand Barrels per Day),Alaska North Slope Crude Oil Production (Thousand Barrels per Day),Arizona Field Production of Crude Oil (Thousand Barrels per Day),California Field Production of Crude Oil (Thousand Barrels per Day),Nevada Field Production of Crude Oil (Thousand Barrels per Day),Federal Offshore PADD 5 Field Production of Crude Oil (Thousand Barrels per Day)
1200,2020-01-15,12755,78.0,5.0,1.0,19.0,0.0,54.0,2149.0,24.0,...,98.0,288.0,922.0,482.0,14.0,468.0,0.0,426.0,1.0,14.0
1201,2020-02-15,12746,77.0,5.0,1.0,18.0,0.0,54.0,2204.0,22.0,...,97.0,277.0,917.0,477.0,14.0,463.0,0.0,427.0,0.0,13.0
1202,2020-03-15,12737,71.0,5.0,1.0,15.0,0.0,50.0,2166.0,21.0,...,98.0,283.0,905.0,470.0,13.0,456.0,0.0,421.0,1.0,13.0
1203,2020-04-15,11990,61.0,4.0,1.0,14.0,0.0,42.0,1887.0,15.0,...,86.0,245.0,879.0,463.0,14.0,449.0,0.0,409.0,1.0,6.0
1204,2020-05-15,10001,60.0,4.0,1.0,14.0,0.0,41.0,1380.0,11.0,...,73.0,165.0,803.0,404.0,12.0,393.0,0.0,392.0,0.0,6.0

In [12]:
data.iloc[-1]

Date                                                                                         2020-05-15 00:00:00
U.S. Field Production of Crude Oil (Thousand Barrels per Day)                                              10001
East Coast (PADD 1) Field Production of Crude Oil (Thousand Barrels per Day)                                  60
Florida Field Production of Crude Oil (Thousand Barrels per Day)                                               4
New York Field Production of Crude Oil (Thousand Barrels per Day)                                              1
Pennsylvania Field Production of Crude Oil (Thousand Barrels per Day)                                         14
Virginia Field Production of Crude Oil (Thousand Barrels per Day)                                              0
West Virginia Field Production of Crude Oil (Thousand Barrels per Day)                                        41
Midwest (PADD 2) Field Production of Crude Oil (Thousand Barrels per Day)                                   1380
Illinois Field Production of Crude Oil (Thousand Barrels per Day)                                             11
Indiana Field Production of Crude Oil (Thousand Barrels per Day)                                               2
Kansas Field Production of Crude Oil (Thousand Barrels per Day)                                               66
Kentucky Field Production of Crude Oil (Thousand Barrels per Day)                                              7
Michigan Field Production of Crude Oil (Thousand Barrels per Day)                                              4
Missouri Field Production of Crude Oil (Thousand Barrels per Day)                                              0
Nebraska Field Production of Crude Oil (Thousand Barrels per Day)                                              2
North Dakota Field Production of Crude Oil (Thousand Barrels per Day)                                        862
Ohio Field Production of Crude Oil (Thousand Barrels per Day)                                                 60
Oklahoma Field Production of Crude Oil (Thousand Barrels per Day)                                            363
South Dakota Field Production of Crude Oil (Thousand Barrels per Day)                                          2
Tennessee Field Production of Crude Oil (Thousand Barrels per Day)                                             0
Gulf Coast (PADD 3) Field Production of Crude Oil (Thousand Barrels per Day)                                7009
Alabama Field Production of Crude Oil (Thousand Barrels per Day)                                               6
Arkansas Field Production of Crude Oil (Thousand Barrels per Day)                                             10
Louisiana Field Production of Crude Oil (Thousand Barrels per Day)                                            76
Mississippi Field Production of Crude Oil (Thousand Barrels per Day)                                          24
New Mexico Field Production of Crude Oil (Thousand Barrels per Day)                                          885
Texas Field Production of Crude Oil (Thousand Barrels per Day)                                              4395
Federal Offshore--Gulf of Mexico Field Production of Crude Oil (Thousand Barrels per Day)                   1613
Rocky Mountain (PADD 4) Field Production of Crude Oil (Thousand Barrels per Day)                             749
Colorado Field Production of Crude Oil (Thousand Barrels per Day)                                            471
Idaho Field Production of Crude Oil (Thousand Barrels per Day)                                                 0
Montana Field Production of Crude Oil (Thousand Barrels per Day)                                              41
Utah Field Production of Crude Oil (Thousand Barrels per Day)                                                 73
Wyoming Field Production of Crude Oil (Thousand Barrels per Day)                                             165
West Coast (PADD 5) Field Production of Crude Oil (Thousand Barrels per Day)                                 803
Alaska Field Production of Crude Oil (Thousand Barrels per Day)                                              404
Alaska South Field Production of Crude Oil (Thousand Barrels per Day)                                         12
Alaska North Slope Crude Oil Production (Thousand Barrels per Day)                                           393
Arizona Field Production of Crude Oil (Thousand Barrels per Day)                                               0
California Field Production of Crude Oil (Thousand Barrels per Day)                                          392
Nevada Field Production of Crude Oil (Thousand Barrels per Day)                                                0
Federal Offshore PADD 5 Field Production of Crude Oil (Thousand Barrels per Day)                               6
Name: 1204, dtype: object

In [13]:
# I only want data from 2000 and on up
data=data.loc[data['Date']>='2000']

In [14]:
data.mean()

U.S. Field Production of Crude Oil (Thousand Barrels per Day)                                7052.053061
East Coast (PADD 1) Field Production of Crude Oil (Thousand Barrels per Day)                   32.526531
Florida Field Production of Crude Oil (Thousand Barrels per Day)                                6.579592
New York Field Production of Crude Oil (Thousand Barrels per Day)                               0.828571
Pennsylvania Field Production of Crude Oil (Thousand Barrels per Day)                          11.110204
Virginia Field Production of Crude Oil (Thousand Barrels per Day)                               0.000000
West Virginia Field Production of Crude Oil (Thousand Barrels per Day)                         14.048980
Midwest (PADD 2) Field Production of Crude Oil (Thousand Barrels per Day)                    1028.208163
Illinois Field Production of Crude Oil (Thousand Barrels per Day)                              26.506122
Indiana Field Production of Crude Oil (Thousand Barrels per Day)                                5.302041
Kansas Field Production of Crude Oil (Thousand Barrels per Day)                               104.097959
Kentucky Field Production of Crude Oil (Thousand Barrels per Day)                               7.163265
Michigan Field Production of Crude Oil (Thousand Barrels per Day)                              17.575510
Missouri Field Production of Crude Oil (Thousand Barrels per Day)                               0.110204
Nebraska Field Production of Crude Oil (Thousand Barrels per Day)                               6.877551
North Dakota Field Production of Crude Oil (Thousand Barrels per Day)                         536.632653
Ohio Field Production of Crude Oil (Thousand Barrels per Day)                                  29.967347
Oklahoma Field Production of Crude Oil (Thousand Barrels per Day)                             288.897959
South Dakota Field Production of Crude Oil (Thousand Barrels per Day)                           4.020408
Tennessee Field Production of Crude Oil (Thousand Barrels per Day)                              0.951020
Gulf Coast (PADD 3) Field Production of Crude Oil (Thousand Barrels per Day)                 4187.840816
Alabama Field Production of Crude Oil (Thousand Barrels per Day)                               21.934694
Arkansas Field Production of Crude Oil (Thousand Barrels per Day)                              16.926531
Louisiana Field Production of Crude Oil (Thousand Barrels per Day)                            198.224490
Mississippi Field Production of Crude Oil (Thousand Barrels per Day)                           56.571429
New Mexico Field Production of Crude Oil (Thousand Barrels per Day)                           306.959184
Texas Field Production of Crude Oil (Thousand Barrels per Day)                               2112.575510
Federal Offshore--Gulf of Mexico Field Production of Crude Oil (Thousand Barrels per Day)    1474.702041
Rocky Mountain (PADD 4) Field Production of Crude Oil (Thousand Barrels per Day)              493.559184
Colorado Field Production of Crude Oil (Thousand Barrels per Day)                             178.979592
Idaho Field Production of Crude Oil (Thousand Barrels per Day)                                  0.049689
Montana Field Production of Crude Oil (Thousand Barrels per Day)                               69.289796
Utah Field Production of Crude Oil (Thousand Barrels per Day)                                  69.546939
Wyoming Field Production of Crude Oil (Thousand Barrels per Day)                              175.714286
West Coast (PADD 5) Field Production of Crude Oil (Thousand Barrels per Day)                 1309.926531
Alaska Field Production of Crude Oil (Thousand Barrels per Day)                               674.040816
Alaska South Field Production of Crude Oil (Thousand Barrels per Day)                          17.710204
Alaska North Slope Crude Oil Production (Thousand Barrels per Day)                            656.314286
Arizona Field Production of Crude Oil (Thousand Barrels per Day)                                0.000000
California Field Production of Crude Oil (Thousand Barrels per Day)                           579.787755
Nevada Field Production of Crude Oil (Thousand Barrels per Day)                                 1.122449
Federal Offshore PADD 5 Field Production of Crude Oil (Thousand Barrels per Day)               54.926531
dtype: float64

In [15]:
data.head()
# remove unit measurement from headers
actual =[string.replace('Field Production of Crude Oil (Thousand Barrels per Day)','').rstrip() for string in data.columns]
data.columns=actual
actual =[string.replace('Crude Oil Production (Thousand Barrels per Day)','').rstrip() for string in data.columns]
data.columns=actual

In [16]:
# add states that do not produce oil for mapping purposes
data['New Jersey'] = 0
data['Georgia'] = 0
data['South Carolina'] = 0
data['North Carolina'] = 0
data['Delaware'] = 0
data['Maryland'] =0
data['Vermont']=0
data['New Hampshire']=0
data['Rhode Island']=0
data['Massachusetts']=0
data['Connecticut']=0
data['Maine']=0
data['Washington']=0
data['Oregon']=0
data['Wisconsin'] = 0
data['Minnesota']=0
data['Iowa']=0

In [17]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 245 entries, 960 to 1204
Data columns (total 60 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Date                              245 non-null    datetime64[ns]
 1   U.S.                              245 non-null    int64
 2   East Coast (PADD 1)               245 non-null    float64
 3   Florida                           245 non-null    float64
 4   New York                          245 non-null    float64
 5   Pennsylvania                      245 non-null    float64
 6   Virginia                          245 non-null    float64
 7   West Virginia                     245 non-null    float64
 8   Midwest (PADD 2)                  245 non-null    float64
 9   Illinois                          245 non-null    float64
 10  Indiana                           245 non-null    float64
 11  Kansas                            245 non-null    float64
 12  Kentucky                          245 non-null    float64
 13  Michigan                          245 non-null    float64
 14  Missouri                          245 non-null    float64
 15  Nebraska                          245 non-null    float64
 16  North Dakota                      245 non-null    float64
 17  Ohio                              245 non-null    float64
 18  Oklahoma                          245 non-null    float64
 19  South Dakota                      245 non-null    float64
 20  Tennessee                         245 non-null    float64
 21  Gulf Coast (PADD 3)               245 non-null    float64
 22  Alabama                           245 non-null    float64
 23  Arkansas                          245 non-null    float64
 24  Louisiana                         245 non-null    float64
 25  Mississippi                       245 non-null    float64
 26  New Mexico                        245 non-null    float64
 27  Texas                             245 non-null    float64
 28  Federal Offshore--Gulf of Mexico  245 non-null    float64
 29  Rocky Mountain (PADD 4)           245 non-null    float64
 30  Colorado                          245 non-null    float64
 31  Idaho                             161 non-null    float64
 32  Montana                           245 non-null    float64
 33  Utah                              245 non-null    float64
 34  Wyoming                           245 non-null    float64
 35  West Coast (PADD 5)               245 non-null    float64
 36  Alaska                            245 non-null    float64
 37  Alaska South                      245 non-null    float64
 38  Alaska North Slope                245 non-null    float64
 39  Arizona                           245 non-null    float64
 40  California                        245 non-null    float64
 41  Nevada                            245 non-null    float64
 42  Federal Offshore PADD 5           245 non-null    float64
 43  New Jersey                        245 non-null    int64
 44  Georgia                           245 non-null    int64
 45  South Carolina                    245 non-null    int64
 46  North Carolina                    245 non-null    int64
 47  Delaware                          245 non-null    int64
 48  Maryland                          245 non-null    int64
 49  Vermont                           245 non-null    int64
 50  New Hampshire                     245 non-null    int64
 51  Rhode Island                      245 non-null    int64
 52  Massachusetts                     245 non-null    int64
 53  Connecticut                       245 non-null    int64
 54  Maine                             245 non-null    int64
 55  Washington                        245 non-null    int64
 56  Oregon                            245 non-null    int64
 57  Wisconsin                         245 non-null    int64
 58  Minnesota                         245 non-null    int64
 59  Iowa                              245 non-null    int64
dtypes: datetime64[ns](1), float64(41), int64(18)
memory usage: 116.8 KB

In [18]:
data.tail(10)

,Date,U.S.,East Coast (PADD 1),Florida,New York,Pennsylvania,Virginia,West Virginia,Midwest (PADD 2),Illinois,...,New Hampshire,Rhode Island,Massachusetts,Connecticut,Maine,Washington,Oregon,Wisconsin,Minnesota,Iowa
1195,2019-08-15,12425,74.0,5.0,1.0,18.0,0.0,51.0,2260.0,23.0,...,0,0,0,0,0,0,0,0,0,0
1196,2019-09-15,12495,78.0,5.0,1.0,19.0,0.0,53.0,2267.0,23.0,...,0,0,0,0,0,0,0,0,0,0
1197,2019-10-15,12673,83.0,5.0,1.0,19.0,0.0,58.0,2332.0,23.0,...,0,0,0,0,0,0,0,0,0,0
1198,2019-11-15,12860,79.0,5.0,1.0,18.0,0.0,55.0,2316.0,23.0,...,0,0,0,0,0,0,0,0,0,0
1199,2019-12-15,12802,76.0,5.0,1.0,18.0,0.0,52.0,2277.0,24.0,...,0,0,0,0,0,0,0,0,0,0
1200,2020-01-15,12755,78.0,5.0,1.0,19.0,0.0,54.0,2149.0,24.0,...,0,0,0,0,0,0,0,0,0,0
1201,2020-02-15,12746,77.0,5.0,1.0,18.0,0.0,54.0,2204.0,22.0,...,0,0,0,0,0,0,0,0,0,0
1202,2020-03-15,12737,71.0,5.0,1.0,15.0,0.0,50.0,2166.0,21.0,...,0,0,0,0,0,0,0,0,0,0
1203,2020-04-15,11990,61.0,4.0,1.0,14.0,0.0,42.0,1887.0,15.0,...,0,0,0,0,0,0,0,0,0,0
1204,2020-05-15,10001,60.0,4.0,1.0,14.0,0.0,41.0,1380.0,11.0,...,0,0,0,0,0,0,0,0,0,0

In [19]:
# transform data to assign PADD region and state location to each value for each date
production=pd.DataFrame()
for col in data.columns.drop(['Date']):
    section=pd.DataFrame()
    section['date']=data['Date']
    section['location']=col
    section['production']=data[col]
    production=production.append(section)

In [20]:
production.head()

          date location  production
960 2000-01-15     U.S.      5784.0
961 2000-02-15     U.S.      5852.0
962 2000-03-15     U.S.      5918.0
963 2000-04-15     U.S.      5854.0
964 2000-05-15     U.S.      5847.0

In [21]:
data.columns

Index(['Date', 'U.S.', 'East Coast (PADD 1)', 'Florida', 'New York',
       'Pennsylvania', 'Virginia', 'West Virginia', 'Midwest (PADD 2)',
       'Illinois', 'Indiana', 'Kansas', 'Kentucky', 'Michigan', 'Missouri',
       'Nebraska', 'North Dakota', 'Ohio', 'Oklahoma', 'South Dakota',
       'Tennessee', 'Gulf Coast (PADD 3)', 'Alabama', 'Arkansas', 'Louisiana',
       'Mississippi', 'New Mexico', 'Texas',
       'Federal Offshore--Gulf of Mexico', 'Rocky Mountain (PADD 4)',
       'Colorado', 'Idaho', 'Montana', 'Utah', 'Wyoming',
       'West Coast (PADD 5)', 'Alaska', 'Alaska South', 'Alaska North Slope',
       'Arizona', 'California', 'Nevada', 'Federal Offshore PADD 5',
       'New Jersey', 'Georgia', 'South Carolina', 'North Carolina', 'Delaware',
       'Maryland', 'Vermont', 'New Hampshire', 'Rhode Island', 'Massachusetts',
       'Connecticut', 'Maine', 'Washington', 'Oregon', 'Wisconsin',
       'Minnesota', 'Iowa'],
      dtype='object')

In [22]:
# add PADD location
PADD_matching={'Florida':'PADD 1',
               'New York':'PADD 1',
               'Pennsylvania':'PADD 1',
               'Virginia':'PADD 1',
               'West Virginia':'PADD 1',
               'New Jersey':'PADD 1',
               'Georgia':'PADD 1',
               'South Carolina':'PADD 1',
               'North Carolina':'PADD 1',
               'Delaware':'PADD 1',
               'Maryland':'PADD 1',
               'Vermont':'PADD 1',
               'New Hampshire':'PADD 1',
               'Rhode Island':'PADD 1',
               'Connecticut':'PADD 1',
               'Massachusetts':'PADD 1',
               'Maine':'PADD 1',
               'Wisconsin':'PADD 2',
               'Minnesota':'PADD 2',
               'Iowa':'PADD 2',
               'Oregon':'PADD 5',
               'Washington':'PADD 5',
               'Illinois':'PADD 2',
               'Indiana':'PADD 2',
               'Kansas':'PADD 2',
               'Kentucky':'PADD 2',
               'Michigan':'PADD 2',
               'Missouri':'PADD 2',
               'Nebraska':'PADD 2',
               'North Dakota':'PADD 2',
               'Ohio':'PADD 2',
               'Oklahoma':'PADD 2',
               'South Dakota':'PADD 2',
               'Tennessee':'PADD 2',
               'Alabama':'PADD 3',
               'Arkansas':'PADD 3',
               'Louisiana':'PADD 3',
               'Mississippi':'PADD 3',
               'New Mexico':'PADD 3',
               'Texas':'PADD 3',
               'Federal Offshore--Gulf of Mexico':'PADD 3',
               'Colorado':'PADD 4',
               'Idaho':'PADD 4',
               'Montana':'PADD 4',
               'Utah':'PADD 4',
               'Wyoming':'PADD 4',
               'Alaska':'PADD 5',
               'Alaska South':'PADD 5',
               'Alaska North Slope':'PADD 5',
               'Arizona':'PADD 5',
               'California':'PADD 5',
               'Nevada':'PADD 5',
               'Federal Offshore PADD 5':'PADD 5'
              }

In [23]:
# using pandas mapping function
production['PADD location'] = production['location'].map(PADD_matching)

In [24]:
# add overall country tag.  allows for overall production analysis
production['Country'] = 'United States'

In [25]:
production.tail()

           date location  production PADD location        Country
1200 2020-01-15     Iowa         0.0        PADD 2  United States
1201 2020-02-15     Iowa         0.0        PADD 2  United States
1202 2020-03-15     Iowa         0.0        PADD 2  United States
1203 2020-04-15     Iowa         0.0        PADD 2  United States
1204 2020-05-15     Iowa         0.0        PADD 2  United States

In [26]:
# save transformed data
production.to_csv('usa_production.csv',index=False)

In [27]:
# save original data fromm 2000 and all up
data.to_csv('production_columns.csv',index=False)